/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_VentanaCitas;

/**
 *
 * @author Moon
 */
public class FRM_VentanaCitas extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaCitas
     */
    Controlador_FRM_VentanaCitas controlador;
    int cita=1;
    
    public FRM_VentanaCitas() {
        initComponents();
        controlador=new Controlador_FRM_VentanaCitas(this);
        agregarEventos();
        deshabilitarCita();
    }
    
    public void agregarEventos()
    {
        this.jb_Registrar.addActionListener(controlador);
        this.jb_Cancelar.addActionListener(controlador);
        this.jb_Reportes.addActionListener(controlador);
        this.jb_Siguiente.addActionListener(controlador);
        this.jB_MayorAMenor.addActionListener(controlador);
        this.jB_MenorAMayor.addActionListener(controlador);
        this.jb_Modificar.addActionListener(controlador);
    }
    
    public int generarNumeroCita(boolean registrarse)
    {
        if(registrarse)
        {
          cita++;  
        }
        else
        {
          cita=cita;  
        }
        this.jt_Cita.setText(""+cita);
        return cita;
    }
    
     public String[] devolverInformacion()
    {
        String[] arreglo=new String[6];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_Nombre.getText();
        arreglo[2]=this.jt_Edad.getText();    
        arreglo[3]=""+this.jcb_Prioridad.getSelectedItem();
        arreglo[4]=this.jt_Cita.getText();
        arreglo[5]=this.jt_FechaCita.getText();
        return arreglo;
    }
     
     public String devolverCedula()
     {
        return this.jt_CedulaEliminar.getText();
     }
     public String devolverCedulaIn()
     {
         return this.jt_Cedula.getText();
     }
     public String devolverNombre()
     {
         return this.jt_Nombre.getText();
     }
     public int devolverEdad()
     {
         int edad=Integer.parseInt(this.jt_Edad.getText());
         
         return edad;
     }
     public String devolverFecha()
     {
         return this.jt_FechaCita.getText();
     }
     public void deshabilitarCita()
    {
        this.jt_Cita.setEnabled(false);
    }
    
    public void imprimir(String siguiente)
    {        
        this.jta_CajaTexto.setText(siguiente);
    }
    public String devolverPrioridad()
    {
        return ""+this.jcb_Prioridad.getSelectedItem();
    }
    public void limpiarVentana()
    {
        this.jt_Edad.setText("");
        this.jt_Nombre.setText("");
        this.jt_Cedula.setText("");
        this.jcb_Prioridad.setSelectedItem("Normal");
        this.jt_FechaCita.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cita = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jt_Cita = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jcb_Prioridad = new javax.swing.JComboBox<>();
        jb_Registrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_CajaTexto = new javax.swing.JTextArea();
        jl_atendiendoA = new javax.swing.JLabel();
        jb_Siguiente = new javax.swing.JButton();
        jb_Cancelar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jb_Reportes = new javax.swing.JButton();
        jl_Ordenar = new javax.swing.JLabel();
        jB_MayorAMenor = new javax.swing.JButton();
        jB_MenorAMayor = new javax.swing.JButton();
        jl_Fecha = new javax.swing.JLabel();
        jt_FechaCita = new javax.swing.JTextField();
        jl_EliminarConCed = new javax.swing.JLabel();
        jl_cedulaEliminar = new javax.swing.JLabel();
        jt_CedulaEliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Cita.setText("Cita");

        jl_Cedula.setText("Cédula");

        jl_Nombre.setText("Nombre");

        jl_Edad.setText("Edad");

        jLabel5.setText("Prioridad");

        jt_Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CitaActionPerformed(evt);
            }
        });

        jt_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_EdadActionPerformed(evt);
            }
        });

        jcb_Prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Ley 7600" }));

        jb_Registrar.setText("Registrar");

        jta_CajaTexto.setColumns(20);
        jta_CajaTexto.setRows(5);
        jScrollPane1.setViewportView(jta_CajaTexto);

        jl_atendiendoA.setText("Atendiendo a:");

        jb_Siguiente.setText("Siguiente");

        jb_Cancelar.setText("Cancelar cita");
        jb_Cancelar.setActionCommand("Cancelar");

        jb_Modificar.setText("Modificar");
        jb_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarActionPerformed(evt);
            }
        });

        jb_Reportes.setText("Reportes");

        jl_Ordenar.setText("Ordenar por edad");

        jB_MayorAMenor.setText("Mayor a menor");

        jB_MenorAMayor.setText("Menor a mayor");

        jl_Fecha.setText("Fecha");

        jl_EliminarConCed.setText("Cancelar cita con cédula");

        jl_cedulaEliminar.setText("Cédula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Nombre)
                            .addComponent(jl_Edad))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_Edad)
                            .addComponent(jt_Nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Cedula)
                            .addComponent(jl_Cita))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_Cedula)
                            .addComponent(jt_Cita)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jl_Fecha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_Prioridad, 0, 117, Short.MAX_VALUE)
                            .addComponent(jt_FechaCita)))
                    .addComponent(jb_Modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jl_EliminarConCed)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jl_cedulaEliminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jt_CedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb_Cancelar)
                                .addGap(104, 104, 104)))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jl_atendiendoA))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jb_Siguiente)
                                        .addGap(84, 84, 84)
                                        .addComponent(jb_Reportes))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jl_Ordenar)
                                        .addGap(12, 12, 12))
                                    .addComponent(jB_MenorAMayor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jB_MayorAMenor, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_atendiendoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jB_MayorAMenor)
                                .addGap(29, 29, 29)
                                .addComponent(jB_MenorAMayor))
                            .addComponent(jl_Ordenar))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Siguiente)
                            .addComponent(jb_Reportes))
                        .addGap(31, 31, 31)
                        .addComponent(jl_EliminarConCed)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_CedulaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_cedulaEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_Cancelar)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Cita)
                            .addComponent(jt_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Cedula)
                            .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Nombre)
                            .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Edad)
                            .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jcb_Prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_FechaCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Fecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jb_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_EdadActionPerformed

    private void jt_CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CitaActionPerformed

    private void jb_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaCitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_MayorAMenor;
    private javax.swing.JButton jB_MenorAMayor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Cancelar;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JButton jb_Registrar;
    private javax.swing.JButton jb_Reportes;
    private javax.swing.JButton jb_Siguiente;
    private javax.swing.JComboBox<String> jcb_Prioridad;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Cita;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_EliminarConCed;
    private javax.swing.JLabel jl_Fecha;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Ordenar;
    private javax.swing.JLabel jl_atendiendoA;
    private javax.swing.JLabel jl_cedulaEliminar;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_CedulaEliminar;
    private javax.swing.JTextField jt_Cita;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_FechaCita;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextArea jta_CajaTexto;
    // End of variables declaration//GEN-END:variables
}
